### PR TITLE
Fixes to Export command

### PR DESCRIPTION
**Pull request by justsml**
Sorry I left the comments in, let me know if you want it cleaned up.
Related: #96 #40

### CODE REVIEW

**Comment by justsml** [comment]
Hey @thomasdavis  I didn't mean to include that in the pull, I guess I was really tired... Anyway, my thinking on the menu was that it provides a superfluous layer of choice - the only choice the user needs to make is a filename, that alone lets us know which export method to use (and probably should just default to HTML, unless pdf or other recognized type is detected).

**Comment by justsml** [comment]
Hey guys: 
@rolandnsharp 
@erming 
@thomasdavis 
 1 more thing I meant to add was: the CLI menu should be it's own stand-alone **cli.js** file which interacts with the core lib - it's confusing having bits and pieces of a console menu UI sprinkled throughout.

I'm assuming that if a typical user managed to install and start using the **resume-cli**, that a command interface w/ 1 or 2 parameters won't scare even windows users away... j/k

While I'm sure this stuff *could* be in another pull; let me just hash out some (tangentially) related ideas...
It'd be nice if it made helpful assumptions about the options (even if they are obviously named flags).
Here's some notes on a tightened up CLI command interface: 
```shell
# defaults to resume.html or index.html in current dir
resume export [themeName] [filePath]  
# ^^^ even if the params are 'out of order', it should be relatively easy to detect which is the theme name and which is the filename, i can work on it if you guys think it's a good idea?

# auto open with local http-server
resume view     
                         
# just random todo addition: would be nice if there was a way to list top themes w/ stars and/or download count
resume list-themes      # > Also, this would be a great place for a console menu ;)
```
Copy-and-pasteable command examples like above would be awesome in the **--help**

Also the *register*, *login*, and *publish* cmds should be together & marked separately or indented as it's not immediately obvious that the CLI supports 2 'modes' - one to publish to https://registry.jsonresume.org - and the other (appears) to just use the web service for 'local' use.

Also I'm not sure if the -s option is necessary .. If you don't want a browser to open just export it ... Right?

Anyway, let me know if you guys have any thoughts.

Thanks a bunch!!!!

**Comment by mchelen** [comment]
I agree with taking out the interactive menus. How about seperating that into its own PR? Also there is no reason to comment out code, just delete it. If people want to readd it later, that's what version control is for :)

**Comment by justsml** [comment]
Thanks @mchelen I'll finish the code later tonight ... then I'll do the 2 PRs.

**Comment by mchelen** [comment]
@justsml Great, thanks! These are really good updates, so it would be cool to make them easy to review & merge.

**Comment by justsml** [comment]
Hey guys I think I've got my 2 new PRs ready... Please let me know if I'm forgetting something and I'll take care of it... (Or if I just have bad ideas, I'll understand if its 'out of scope' )

**Comment by justsml** [comment]
Damn... Meant previous post on the new PRs... 

Everyone subscribing/watching gets notified, even if the PR is closed, right?

**Pull request closed without merging**
