### PR TITLE
style(lint): using eslint-plugin-prettier so prettier and eslint will not fight

### PR DESCRIPTION
**Pull request by antialias**

### CODE REVIEW

**Comment by thomasdavis** [comment]
LGTM

**Review by rbardini — COMMENTED** [review]
I wouldn't recommend using `eslint-plugin-prettier` for the [reasons listed in their website](https://prettier.io/docs/en/integrating-with-linters.html#notes). Turning off conflicting rules with `eslint-config-prettier` + `"extends": ["eslint:recommended", "prettier"]` and running Prettier separately on save/commit should be better.

We also don't need to make Prettier rules errors as long as we check format on CI, which was reverted in 6ea90af, probably to unblock older PRs.

**Comment by antialias** [comment]
In the same sentence, the docs also say that integration with a linter "can be useful in certain circumstances". My motivation behind this PR is twofold:

1. I'd like my editor to surface prettier messages and / or use prettier to format my code.
1. reduce proliferation of ci / git hook scripts as I'm not completely sold on the benefits of keeping separate scripts for lint and format checking.

for #1 I just enabled prettier as a fixer in my .vimrc, so that issue may be addressed. I can't speak for users of other editors, but it appears that most editors have introduced prettier integration at this point.

I do not see a great solution to #2. The choice is to either integrate prettier with `eslint`, or run `prettier [--check]` before `eslint` at every place where it matters. (Whatever we choose, the codebase needs to be updated since in master we apparently aren't running `prettier --check` on CI anymore.)

> I wouldn't recommend using `eslint-plugin-prettier` for the [reasons listed in their website](https://prettier.io/docs/en/integrating-with-linters.html#notes).

**Comment by antialias** [comment]
At the risk of sounding "passionate", I wanted to follow up by going through the downsides that are listed on the prettier docs, since they didn't seem to be very significant, but before I do that, understand that I'm fine with tabling this PR for a while if we can get the [ci checks](https://github.com/jsonresume/resume-cli/blob/master/.github/workflows/main.yml#L24) agreeing with with the [git hooks](https://github.com/jsonresume/resume-cli/blob/master/.lintstagedrc.json).

> You end up with a lot of red squiggly lines in your editor, which gets annoying. Prettier is supposed to make you forget about formatting – and not be in your face about it!

The squiggly lines go away pretty fast if you have have your editor run `eslint --fix` when a file is a changed.

> They are slower than running Prettier directly.

I really haven't experienced performance issues using eslint-plugin-prettier with vim + [`ALE`](https://github.com/dense-analysis/ale). Is it slow in your editor?

> They’re yet one layer of indirection where things may break.

I don't see how running prettier as a separate script for every ci / hook / editor configuration is simpler. I've been using the eslint-plugin-prettier for years in multiple projects and in multiple contexts and it has never broken.

**Comment by rbardini** [comment]
From my personal experience with a larger codebase, running Prettier inside ESLint heavily slows down the linting process (~50% of the time taken by `prettier/prettier` rule, according to the [built-in performance tracking](https://eslint.org/docs/1.0.0/developer-guide/working-with-rules#per-rule-performance)). We have since decoupled Prettier from ESLint by disabling conflicting rules with `eslint-config-prettier` and running Prettier in a pre-commit hook and in the CI (and optionally in editors).

It might not be very noticeable in a smaller codebase like this, but I still believe it provides a better workflow. I'd say it's liberating to not have code highlighted because it's not following Prettier's style, nor having to constantly save files to make it go away. This is from a macOS user though, not sure if the hooks setup has problems in other environments.

Anyway, just my two cents. I'm not completely against this PR—I agree we either need this or to restore the Prettier check in the CI.

**Comment by antialias** [comment]
# Testing eslint and prettier performance on my own workstation:

## running eslint and prettier separately (branch for this PR)
```sh
➜  resume-cli git:(eslint-plugin-prettier) ✗ time seq 100 | xargs -I -- npm run lint
seq 100  0.00s user 0.00s system 72% cpu 0.003 total
xargs -I -- npm run lint  155.40s user 19.84s system 126% cpu 2:18.01 total
```
^ average time for eslint (w/ eslint-plugin-prettier) **1.54 seconds**.

## running prettier checks inside of eslint (master)
```sh
➜  resume-cli git:(master) ✗ time seq 100 | xargs -I -- npm run lint
xargs -I -- npm run lint  97.57s user 14.44s system 117% cpu 1:35.13 total
```
^ average time for `eslint`: .97 seconds

```sh
➜  resume-cli git:(master) ✗ time seq 100 | xargs -I -- npm run format:check
xargs -I -- npm run format:check  340.70s user 11.39s system 147% cpu 3:58.69 total
```

^ average time for `prettier --check`: 3.4 seconds

total time for `eslint` + `prettier --check`: **4.37 seconds**.

# (shocking) summary:

Running eslint and prettier separately takes 183% _longer_ than running prettier as a plugin of eslint.

# my recomendation
The codebase on master is relatively small at the moment, and my prediction is that it's going to be smaller in the next few weeks as the resume importers and exporters are factored out into their own modules. Adding prettier into the eslint run takes only half a second longer than leaving it out, i.e. the time penalty by including prettier in the eslint run is insignificant in my opinion, and will continue to be that way with the current plan for the codebase.

My recommendation is to keep the scripts in package.json, .github/workflow, and .huskyrc as few and small as possible, and combining prettier and eslint does this.

At the end of the day, the decision is up to @thomasdavis since the cli is their project. I'm just providing data and opinions here :)

**Comment by antialias** [comment]
It's been a couple of weeks since I posted my last comment on this PR. Since the state of CI checks is currently inconsistent with the git hooks, and this PR would solve that by integrating eslint and prettier, I'm inclined to merge, so that is what I will do 24 hours from now (Tuesday evening, Dec 29th). Happy to revert and rethink the changs here continue to raise a serious issue for anyone.

**Pull request merged**
