### PR TITLE
major(theme): use jsonresume-theme-even by default

### PR DESCRIPTION
**Pull request by rbardini**
[jsonresume-theme-even](https://github.com/rbardini/jsonresume-theme-even) is a flat theme based on [jsonresume-theme-flat](https://github.com/erming/jsonresume-theme-flat), compatible with the latest resume schema. It was forked to add support for projects (https://github.com/jsonresume/resume-schema/pull/254) and fix vulnerability issues, as the original repository seems to be inactive. It is used by a few [dependents](https://github.com/rbardini/jsonresume-theme-even/network/dependents) and is the default theme of [@rbardini/resume-cli](https://www.npmjs.com/package/@rbardini/resume-cli) package, whose changes I'm trying to incorporate back here via separate PRs. See a [working example](https://github.com/rbardini/resume.rbardini.com).

I've also removed all preinstalled themes but the default one. I believe the CLI should be lightweight and easy to maintain. You can check how many packages have been removed from the lockfile with this change. I plan to drop the Handlebars dependency from jsonresume-theme-even at some point, so even fewer dependencies would be installed.

Because replacing the default theme is a breaking change, it's a good opportunity to remove extra themes and reduce the package footprint.

### CODE REVIEW

**Comment by antialias** [comment]
I’ll defer to @thomasdavis for this review and will make a note to check back in a few weeks.

**Comment by thomasdavis** [comment]
I think this is great and happy to merge. 

awesome work @rbardini

**Comment by thomasdavis** [comment]
@rbardini I've given you collaborator access so you can merge these when your happy

**Comment by rbardini** [comment]
Thanks, @thomasdavis! I'll fix conflicts and merge right away.

**Pull request merged**
