### PR TITLE
Local export

### PR DESCRIPTION
**Pull request by astephen2**
- Downgraded async version because it appears to have broken the build
- Changed HTML export to a local, client-side version instead of pushing to a remote server
- Used html-pdf library to create a working version of a client-side pdf export. The exports don't always look clean, but they look the same they would in a browser print. Themes should have a special `@media print` viewpoint to help make them look good when in PDF.

Happy to talk through any of these changes!

### CODE REVIEW

**Comment by astephen2** [comment]
This is a pretty major change, so I'd love some more opinions + testing on it!

**Comment by GabLeRoux** [comment]
Code looks fine to me, but not quite sure about the async lib downgrade. The export to pdf from server side is broken anyway, I think this is a suitable change.

**Comment by thomasdavis** [comment]
@astephen2 Sorry for never getting back to you. This is a great change and a step in the right direction. The only problem being is that they have to have the theme installed globally locally on their computer. If it isn't present it just throws an error, we can catch that error and say that you have to type `npm install -g jsonresume-theme-thin` and try again.

**Comment by thomasdavis** [comment]
Also the CLI tool isn't updated much and I think you can more liberally just merge in your work as it seems to be based off conversations where there is a general consensus anyway.

**Comment by astephen2** [comment]
Sounds good! I've been on vacation for a couple weeks, so I haven't been paying too much attention to Github.

**Pull request merged**
