### PR TITLE
Fix/security

### PR DESCRIPTION
**Pull request by MarcLoupias**
This PR handle the direct dependencies with vulnerabilities listed in #289.

There is still job to be done but we need to fix first the following packages : 

- [jamesperet/jsonresume-theme-crisp](https://github.com/jamesperet/jsonresume-theme-crisp)
- [jsonresume-theme-modern](https://github.com/jsonresume/jsonresume-theme-modern)
- [jsonresume-theme-flat](https://github.com/erming/jsonresume-theme-flat)
- resume-to-html (this one lead to a 404 on github)
- [resume-to-text](https://github.com/rolandnsharp/resumeToText)

### CODE REVIEW

**Comment by MarcLoupias** [comment]
Mmh super weird ...

```
> node node_modules/mocha/bin/mocha --exit test test/*.js
  Register tests
email not found
registering user
e.org/test436.4821556704209'
You can now type: `resume publish` to publish your resume to this domain.
    ✓ should register user (769ms)
registering user
    ✓ should fail to register user is the email already exists in the registry (274ms)
registering user
    ✓ should fail to register user if username already exists (285ms)
pting to login...pting to login...pting to login...pting to login...pting to login...pting to login...pting to login...pting to login...pting to login...pting to login...null { message: 'loggedIn',
  username: 'test436.4821556704209',
  email: 'test123436.4821556704209@test1.com',
  session: 'r6m14y2pmkpe99nv2k49lapws7s9x1s1',
  auth: true }
Success! You are now logged in.
{ message: 'loggedIn',
  username: 'test436.4821556704209',
  email: 'test123436.4821556704209@test1.com',
  session: 'r6m14y2pmkpe99nv2k49lapws7s9x1s1',
  auth: true }
    ✓ should receive a Successful login response (564ms)
    1) should receive a Successful login response
  4 passing (2s)
  1 failing
  1) Register tests
       should receive a Successful login response:
     Uncaught SyntaxError: Unexpected token u in JSON at position 0
      at Object.parse (native)
      at ReadFileContext.callback (lib/login/write-config.js:7:23)
      at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

Can't reproduce it locally. Seems linked to Mocha. Will try to fix it soon.

**Comment by MarcLoupias** [comment]
It is definitely the Mocha update. Will try to fix this soon, don't merge this until i have cleaned that mess :)

**Comment by MarcLoupias** [comment]
Impossible to reproduce the mocha issue locally.

I have tried the node versions used in Travis with mocha@5.2.0 : 

```
"scripts": {
    "test": "node node_modules/mocha/bin/mocha --exit test test/*.js",
    "test-against-node-6": "npx -p node@6.14.4 -- node_modules/mocha/bin/mocha --exit test test/*.js",
    "test-against-node-8": "npx -p node@8.12.0 -- node_modules/mocha/bin/mocha --exit test test/*.js",
    "test-against-node-10": "npx -p node@10.11.0 -- node_modules/mocha/bin/mocha --exit test test/*.js"
  }
```
No problem.

Tested with same node (10.11.0) same npm (6.4.1) with locked deps on the node 10 run and the issue is still there, all green on my computer and fail in CI.

I don't understand, the only diff is with nvm as i don't use it.

I give up, i rollback the Mocha update and clean the history.

**Comment by thomasdavis** [comment]
Great job and great start. Will look into the other repos. Been having fun with Ava later so could swap mocha out.

**Pull request merged**
