### PR TITLE
fix: add full theme path when using local themes on export

### PR DESCRIPTION
**Pull request by Nezteb**
Addresses https://github.com/jsonresume/resume-cli/issues/685 and potentially https://github.com/jsonresume/resume-cli/issues/408

### CODE REVIEW

**Comment by Nezteb** [comment]
FYI @rbardini @antialias

**Comment by Nezteb** [comment]
The lockfile changes are because I get this warning when running `npm install`:
```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
```
I'm on `npm` 8.1.0.

The husky folder is automatically added when I run `npm install`. If it shouldn't be there, I can add it to the `.gitignore` but for now I'm leaving it.

**Review by rbardini — APPROVED** [review]

**Comment by rbardini** [comment]
> The husky folder is automatically added when I run `npm install`. If it shouldn't be there, I can add it to the `.gitignore` but for now I'm leaving it.

`husky@7.0.0` makes `.husky/.gitignore` unnecessary, but upgrading Husky is beyond the scope of this PR 🙂

LGTM!

**Comment by Nezteb** [comment]
@rbardini Is there anything else that needs to be done to get this merged? 😄

**Comment by rbardini** [comment]
@Nezteb sorry for the delay, it's merged now. Thanks for your contribution ❤️

**Pull request merged**
