### PR TITLE
Use Chrome's backend for PDF exports

### PR DESCRIPTION
**Pull request by jceb**
This feature depends on Chrome >=60.

### CODE REVIEW

**Comment by chasebolt** [comment]
i think you are on the right track here with using chrome for pdf creation. possibly use puppeteer instead though since it comes with chromium bundled?

https://github.com/GoogleChrome/puppeteer

**Comment by antialias** [comment]
rendering PDFs with puppeteer appears to be in master. Can we close this PR?

**Comment by jceb** [comment]
Not sure, I haven't tried it yet. However, please go ahead and close this pull request

**Comment by antialias** [comment]
@evanplaice ^

**Comment by thomasdavis** [comment]
Thanks guys. Considering removing PDF generation.

**Comment by antialias** [comment]
> Thanks guys. Considering removing PDF generation.

Reality is that recruiters and hiring managers still work mostly with resumes in PDF format, so as a user of the cli, I would be saddened to see this feature go and be left to do the conversion in a separate step.

The integration with puppeteer can be be implemented better in the code though – in my own fork (resumed) I was able to rewrite it a straightforward manner where it didn’t add complexity to the project. I’ll post a PR when I’m back at a desk in the next few days. I will reference this issue in the PR.

**Comment by thomasdavis** [comment]
Just about selecting better defaults for pupetteer? 

I feel like writing a quick `resume-pdf` library wouldn't be too much extra trouble. 

Would be nice if I could generate some usage stats on the cli. Haven't made a call on pdf removal yet, considering I barely use the cli tool I think pdf might be better kept for those who do.

**Comment by antialias** [comment]
The code that generates a PDF using puppeteer is already in the cli. I have used it quite a bit and it works pretty well. My only comment was that the code could be simplified a bit, and I only said that because I already did it in my fork.

I'll put up a PR for resume-cli tomorrow since this is one of those thing better shown with code.

**Comment by antialias** [comment]
(Deleting my prior comment since I misread yours.)

I could get on board with extracting the pdf export into a custom exporter. The code is so simple. It could remove the puppeteer dependency and reduce the install footprint of the base cli by quite a lot.

The counter argument here is that exporting to PDF is likely so common that in practice, the install footprint would not be reduced since most folks would also install the cost on pdf exporter anyway.

Agreed that usage data would be nice.

**Pull request closed without merging**
