### PR TITLE
build(release)!: automate releases with semantic-release

### PR DESCRIPTION
**Pull request by rbardini**
Run [semantic-release](https://semantic-release.gitbook.io/) from main GitHub Action workflow, so that changes are automatically versioned and published to npm.

Also:

- use dummy `0.0.0-development` package version (the correct version will be determined upon every release)
- update `repository.url` field in `package.json` with organization URL
- use [conventionalcommits](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits) commit-analyzer preset
- ensure PR titles match the [Conventional Commits](https://www.conventionalcommits.org/) spec with [semantic-pull-request](https://github.com/marketplace/actions/semantic-pull-request) GitHub Action
- define `files` field in `package.json` so that dev files (e.g. dotfiles, tests) are not included in the published package
- use sample resume from `resume-schema` when initializing a `resume.json` file
- remove Markdown files from `.gitignore` ignore list

Relates to #359.

### CODE REVIEW

**Comment by rbardini** [comment]
@thomasdavis do you have repository admin permissions, and publishing rights for the npm package? We need to add the `NPM_TOKEN` secret, and restrict merge options to _squash_ only, to make it work 🙂

Also, maybe we could remove the [WIP](https://github.com/marketplace/wip) app, now that GitHub supports [draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/)?

**Comment by thomasdavis** [comment]
Can you shoot me an email at thomasalwyndavis@gmail.com and I will send through an NPM token.

And +1 for GitHub drafts

**Comment by thomasdavis** [comment]
Thanks for the email @rbardini 

- I've added `NPM_TOKEN`
- Only allowed Squash merges 
- And removed the WIP integration 

Let's see how it goes, thanks again.

**Comment by rbardini** [comment]
Thanks @thomasdavis, [it's working](https://github.com/jsonresume/resume-cli/pull/377/checks?check_run_id=995844395):

<details><summary>Release dry-run logs</summary>

```
[10:46:18 PM] [semantic-release] › ℹ  Running semantic-release version 17.1.1
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[10:46:18 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[10:46:21 PM] [semantic-release] › ⚠  Run automated release from branch setup-semantic-release on repository https://github.com/jsonresume/resume-cli.git in dry-run mode
[10:46:21 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[10:46:21 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[10:46:21 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[10:46:21 PM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /tmp/d532fce1cc6bcd45b36f6dd4e5895858/.npmrc
thomasdavis
[10:46:22 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[10:46:22 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[10:46:22 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[10:46:22 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[10:46:22 PM] [semantic-release] › ℹ  Found git tag v1.2.8 associated with version 1.2.8 on branch setup-semantic-release
[10:46:22 PM] [semantic-release] › ℹ  Found 47 commits since last release
[10:46:22 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:46:22 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(release)!: automate releases with semantic-release
[10:46:22 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is major
[10:46:22 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 47 commits complete: major release
[10:46:22 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:46:22 PM] [semantic-release] › ℹ  The next release version is 2.0.0
[10:46:22 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:46:22 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:46:22 PM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/npm" in dry-run mode
[10:46:22 PM] [semantic-release] › ⚠  Skip v2.0.0 tag creation in dry-run mode
[10:46:22 PM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/npm" in dry-run mode
[10:46:22 PM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/github" in dry-run mode
[10:46:22 PM] [semantic-release] › ⚠  Skip step "success" of plugin "@semantic-release/github" in dry-run mode
[10:46:22 PM] [semantic-release] › ✔  Published release 2.0.0 on setup-semantic-release channel
[10:46:22 PM] [semantic-release] › ℹ  Release note for version 2.0.0:
## 2.0.0 (https://github.com/jsonresume/resume-cli/compare/v1.2.8...v2.0.0) (2020-08-17)
```

</details>

Once we merge this, version 2.0.0 should be released, since we have at least one breaking change (#368). The GitHub release changelog won't be perfect, as most commits aren't following the [Conventional Commits](https://www.conventionalcommits.org/) spec, but we can edit it afterwards. Future PRs will have their titles checked to ensure they follow the spec.

I will remove the dry-run and write a `CONTRIBUTING.md` file to clear things up before marking as ready for review 🙂

**Comment by felipecrs** [comment]
I believe the `CONTRIBUTING.md` is not mandatory to have this PR merged.

**Comment by rbardini** [comment]
@thomasdavis I added a `CONTRIBUTING.md` file explaining the release process and conventions to be followed.

I just removed the draft status, so if you approve the changes we can merge this PR, and hopefully a new major version will be released 🙂

**Comment by thomasdavis** [comment]
Beautiful

**Comment by frezbo** [comment]
Is there anything blocking to have this merged? So much excited to see a new release 👍

**Comment by thomasdavis** [comment]
Ahhh my bad, I could of sworn I had reviewed/approved this PR. Just merged it anyway.

**Comment by frezbo** [comment]
@thomasdavis  Awesome thanks.

@rbardini seems the release failed due to invalid token: https://github.com/jsonresume/resume-cli/issues/382, can you please take a look when possible?

**Comment by thomasdavis** [comment]
I will look into it. Pretty sure I already added the token but obviously not.

**Comment by frezbo** [comment]
@thomasdavis Can you check under `Settings` -> `Secrets` under the current repository. The `NPM_TOKEN` should be set there.

**Comment by thomasdavis** [comment]
@frezbo check my comment on https://github.com/jsonresume/resume-cli/issues/382

**Comment by rbardini** [comment]
🎉 🎉 🎉

I'll update the release notes later today, it's missing some changes from previous commits that don't follow the new commit message convention.

**Comment by thomasdavis** [comment]
@rbardini awesome, so sorry about the delay.

Working on a fun side project. AI generated JSON Resumes -> https://fake.jsonresume.org (keep refreshing) (adding generated company data right now)

**Comment by thomasdavis** [comment]
Link above was meant to be no-ssl http://fake.jsonresume.org

**Pull request merged**
