### PR TITLE
Resume Export can reads resume contents from stdin

### LINKED ISSUE #81: Read resume from stdin
I am using jq to modify the json in order to generate custom versions of my resume for different needs.  It would be a nice enhancement if I could simply run "jq < resume.json | resume export --format html" rather then generating a temporary file.

### PR DESCRIPTION
**Pull request by chrisdotcode**
Will close #81.

### CODE REVIEW

**Comment by chrisdotcode** [comment]
Whoops. This still has some errors. Will fix, then add.

**Comment by chrisdotcode** [comment]
Should be ready for merging.

**Comment by chrisdotcode** [comment]
Not ready for merging yet.

**Comment by PeterDaveHello** [comment]
@chrisdotcode please rebase this branch with our latest master branch, thanks.

**Comment by thomasdavis** [comment]
@chrisdotcode is this partially broken? should I fix it?

**Pull request closed without merging**
