### PR TITLE
feat: Allow theme to render with promise

### PR DESCRIPTION
**Pull request by pinage404**
`export` did not support theme who returns promise

```sh
npx resume export resume.html --theme render-with-promise
```

`serve` already support theme who returns promise

```sh
npx resume serve --theme render-with-promise
```

with this PR, both subcommands support it

### CODE REVIEW

**Comment by pinage404** [comment]
There is [already `async` / `await` in the project](https://github.com/jsonresume/resume-cli/blob/5aaf9b8d610e8b4a1e259048e3c58d2630a60da3/lib/export-resume/index.js#L78), so i upgraded to Node 8

**Comment by karlitos** [comment]
MayI ask  what is the current status ? I developed a theme, using "promisedHandlebars", because I convert local or remote images to base64 with the "base64-img" node module which supports only async http requests.

**Comment by pinage404** [comment]
Unfortunately, the project no longer seems to be active

https://github.com/jsonresume/resume-cli/graphs/code-frequency

https://github.com/jsonresume/resume-cli/graphs/contributors

**Comment by karlitos** [comment]
> Unfortunately, the project no longer seems to be active

The same goes for [HackMyResume](https://github.com/hacksalot/HackMyResume). [My own version](https://github.com/karlitos/KissMyResume) supports async rendering. You might try the [theme I build](https://github.com/karlitos/jsonresume-theme-mocha-responsive) utilizing async rendering to create Base64 inline images

**Comment by thomasdavis** [comment]
Re-investigating this one as it makes a lot of sense.

**Comment by thomasdavis** [comment]
Thanks guys!

**Pull request merged**
