### PR TITLE
Simplify export: remove --format parameter and related menu

### PR DESCRIPTION
**Pull request by justsml**
See #96 
Originally discussed in PR #98 
This only partially addresses the interactive menu issue in #100 .. But it should help.

### CODE REVIEW

**Comment by mchelen** [comment]
I like removal of the menus, one reason it might be good to keep --format though is that filename extensions are not strictly required. For example, it's ok to export "resume" and have that file be a PDF format, even if it does not have a .PDF filename extension. But it does also seem redundant to have `export resume.pdf --format=pdf` and can have confusing behavior if doing `export resume.html --format=pdf`.

**Comment by justsml** [comment]
Hi @mchelen I did go back and forth on that a bit... Ultimately I felt that the user is going to be exporting HTML the *vast* majority of the time, so we could safely use it as the default.
Here's example commands which I think clearly defines the adjusted behavior... Hopefully something for the --help output...
```sh
resume -t slick resume          # should assume .html
resume -t slick resume.htm   # equates with .html
resume -t slick resume.pdf    # should use pdf
```
This pattern would also avoid a hard error - if the system assumes nothing, the first example command would need to show/throw an error.

**Comment by mchelen** [comment]
Yup, I see what you mean, and this seems like a reasonable way to go about it.

Does anyone object to merging this?

**Comment by erming** [comment]
This is a lot better than the original solution, in my opinion.

+1

**Comment by justsml** [comment]
Thanks @mchelen  and @erming ... Excellent project!

**Comment by thomasdavis** [comment]
@mchelen no objections

**Comment by rolandnsharp** [comment]
I tested this locally and am getting double filenames on my remumes. eg: resume.html.html

I like @justsml 's convention and this is basically supported apart from defaulting to html.
```
resume -t slick resume          # should assume .html
resume -t slick resume.htm   # equates with .html
resume -t slick resume.pdf    # should use pdf
```
I'm working on a major refactor at the moment and will take out the export interactive menu but to be honest I can't really follow the logic of this code so I'll try to implement it in a way more readable to myself. Thanks for the suggestions.

**Pull request closed without merging**
